#ifndef DESKTOPRECORDER_GLOBAL_H
#define DESKTOPRECORDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DESKTOPRECORDER_LIBRARY)
#  define DESKTOPRECORDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DESKTOPRECORDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DESKTOPRECORDER_GLOBAL_H
